### ISSUE TITLE
Cannot spawn threads with non-primitive arguments

### ISSUE THREAD

**Issue by LeonCalvit** [stevenrbrandt/Mnemosyne#1]
fun printing(args)
	println(args[0])
	println(args[1])
end

fun main()
	regular args := new regular[0, 1]
       # This works fine
	printing(args)
       # This fails
	const th := spawn(printing, args)
	join(th)
end

**Comment by LeonCalvit** [comment]
Threads cannot be spawned with multiple arguments as well, which should be possible.

**Comment by stevenrbrandt** [comment]
Fixed in 89c7174c0d168fd43717f5d5731a31e544c51e7e
